import { Metadata } from "next";
import "./globals.css";
import { ErrorWrapper } from "./error-wrapper";
export const metadata: Metadata = {
  title: {
    default: "Learn Next.js ",
    template: "%s | Learn Next.js",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <p>Header</p>
        </header>
        <ErrorWrapper>
          {children}
          </ErrorWrapper>
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
